name: Pull README.md from the ixo-blockchain repository

on:
  pull_request:
    branches:
      - alwyn-ixopatch-1
jobs:
  pull-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get *.md files from the ixo-blockchain repository
        run: |
          curl -O https://raw.githubusercontent.com/ixofoundation/ixo-blocksync/develop/**/*.md

      - name: Move README.md to destination
        run: |
          mv *.md developers/ixo-blockchain

      - name: Create PR
        uses: actions/create-pull-request@v4
        with:
          title: "Pull .md files from ixo-blockchain"
          body: "This PR pulls the .md files from my-other-repo into the docs directory."
          branch: "${{GITHUB_BRANCH}}"
          base: develop
          files: developers/ixo-blockchain/**/*.md
