name: Copy .md from ixo-blockchain
run-name: ${{ github.actor }} pushed a change.
on: [push]
jobs:
  copy-docs-from-blockchain-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
          path: docs
      - name: Checkout ixo-blockchain
        uses: actions/checkout@v4
        with:
          repository: ixofoundation/ixo-blockchain
          ref: develop
          path: ixo-blockchain
      - run: find ./ixo-blockchain -type f -name "*.md" -print
