name: Copy .md from ixo-blockchain
run-name: ${{ github.actor }} pushed a change.
on: [push]
jobs:
  copy-docs-from-blockchain-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: alwyn-ixopatch-1
      - name: Checkout ixo-blockchain
        uses: actions/checkout@v4
        with:
          repository: ixofoundation/ixo-blockchain
          ref: develop
          path: ixo-blockchain
      - run: ls -al
      - run: find ./ixo-blockchain -type f -name "*.md" -exec cp -R {} . \;
      - run: ls -al
      - run: git add .
      - run: git config --global user.email "ixo@ixo.world"
      - run: git config --global user.name ${{ github.actor }}
      - run: git commit -m "Copy *.md files from ixo-blockchain"
      # - run: git config --global --add safe.directory /home/runner/work/docs/docs
      - run: git push
