name: Copy .md from ixo-blockchain
run-name: ${{ github.actor }} pushed a change.
on: [push]
jobs:
  copy-docs-from-blockchain-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ixofoundation/ixo-blockchain
          ref: develop
